version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - .env

  web:
    build: .
    entrypoint: sh -c "sleep 10 && python manage.py migrate && python manage.py compilemessages && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 80:8000
    networks:
      - my-network
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: redis:7.0.11
    networks:
      - my-network

  worker:
    build: .
    command: celery -A config worker --loglevel=info && celery -A config beat --loglevel=info
    depends_on:
      - redis

volumes:
  postgres_data:

networks:
  my-network: