# Generated by Django 4.2.3 on 2023-08-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ky', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('why_we', models.TextField(max_length=500, verbose_name='Why we')),
                ('why_we_ru', models.TextField(max_length=500, null=True, verbose_name='Why we')),
                ('why_we_ky', models.TextField(max_length=500, null=True, verbose_name='Why we')),
                ('why_we_en', models.TextField(max_length=500, null=True, verbose_name='Why we')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_ky', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='TrialLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ky', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_ky', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Trial Lesson',
                'verbose_name_plural': 'Trial Lessons',
            },
        ),
        migrations.CreateModel(
            name='WhatGive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, verbose_name='What give')),
                ('reason_ru', models.CharField(max_length=100, null=True, verbose_name='What give')),
                ('reason_ky', models.CharField(max_length=100, null=True, verbose_name='What give')),
                ('reason_en', models.CharField(max_length=100, null=True, verbose_name='What give')),
                ('info', models.TextField(verbose_name='Info')),
                ('info_ru', models.TextField(null=True, verbose_name='Info')),
                ('info_ky', models.TextField(null=True, verbose_name='Info')),
                ('info_en', models.TextField(null=True, verbose_name='Info')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_give', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'What Give',
                'verbose_name_plural': 'What Give',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_ky', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('first_name_ru', models.CharField(max_length=100, null=True, verbose_name='First name')),
                ('first_name_ky', models.CharField(max_length=100, null=True, verbose_name='First name')),
                ('first_name_en', models.CharField(max_length=100, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('last_name_ru', models.CharField(max_length=100, null=True, verbose_name='Last name')),
                ('last_name_ky', models.CharField(max_length=100, null=True, verbose_name='Last name')),
                ('last_name_en', models.CharField(max_length=100, null=True, verbose_name='Last name')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_ky', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('photo', models.ImageField(upload_to='mentors/', verbose_name='Photo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
            },
        ),
        migrations.CreateModel(
            name='ForWho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_who', models.TextField(verbose_name='For who')),
                ('for_who_ru', models.TextField(null=True, verbose_name='For who')),
                ('for_who_ky', models.TextField(null=True, verbose_name='For who')),
                ('for_who_en', models.TextField(null=True, verbose_name='For who')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_who', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'For Who',
                'verbose_name_plural': 'For Who',
            },
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('duration_ru', models.CharField(max_length=50, null=True, verbose_name='Duration')),
                ('duration_ky', models.CharField(max_length=50, null=True, verbose_name='Duration')),
                ('duration_en', models.CharField(max_length=50, null=True, verbose_name='Duration')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='courses.course', verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Duration',
                'verbose_name_plural': 'Durations',
            },
        ),
        migrations.CreateModel(
            name='CoursesStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(max_length=100, verbose_name='Stack')),
                ('stack_ru', models.CharField(max_length=100, null=True, verbose_name='Stack')),
                ('stack_ky', models.CharField(max_length=100, null=True, verbose_name='Stack')),
                ('stack_en', models.CharField(max_length=100, null=True, verbose_name='Stack')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_stacks', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Stack',
                'verbose_name_plural': 'Stacks',
            },
        ),
        migrations.CreateModel(
            name='CoursesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='Image')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course image',
                'verbose_name_plural': 'Course images',
            },
        ),
        migrations.CreateModel(
            name='CourseFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=255, verbose_name='Format')),
                ('format_ru', models.CharField(max_length=255, null=True, verbose_name='Format')),
                ('format_ky', models.CharField(max_length=255, null=True, verbose_name='Format')),
                ('format_en', models.CharField(max_length=255, null=True, verbose_name='Format')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_ky', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Format',
                'verbose_name_plural': 'Formats',
            },
        ),
    ]
