# Generated by Django 4.2.3 on 2023-07-25 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(max_length=100, verbose_name='Stack')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_stacks', to='courses.course')),
            ],
            options={
                'verbose_name': 'Stack',
                'verbose_name_plural': 'Stacks',
            },
        ),
    ]
