# Generated by Django 4.2.3 on 2023-07-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursesstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesimage',
            name='image',
            field=models.ImageField(upload_to='courses/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(upload_to='mentors/', verbose_name='Photo'),
        ),
    ]
