# Generated by Django 4.2.3 on 2023-08-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatGive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, verbose_name='What give')),
                ('info', models.TextField(verbose_name='Info')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_give', to='courses.course')),
            ],
            options={
                'verbose_name': 'What give',
                'verbose_name_plural': 'What give',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='Description')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='courses.course')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Program',
            },
        ),
        migrations.CreateModel(
            name='ForWho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_who', models.TextField(verbose_name='For who')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_who', to='courses.course')),
            ],
            options={
                'verbose_name': 'For who',
                'verbose_name_plural': 'For who',
            },
        ),
    ]
