# Generated by Django 4.2.3 on 2023-07-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reviews/', verbose_name='file')),
            ],
        ),
        migrations.RenameField(
            model_name='postdescription',
            old_name='descripton',
            new_name='description',
        ),
    ]
