# Generated by Django 4.2.3 on 2023-08-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusgallery',
            options={'verbose_name': 'About us gallery', 'verbose_name_plural': 'About us gallery'},
        ),
    ]
