# Generated by Django 4.2.3 on 2023-08-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('B', 'Blog'), ('N', 'News'), ('A', 'Best Articles')], default='B', max_length=1, verbose_name='Type'),
        ),
    ]
