# Generated by Django 4.2.3 on 2023-08-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_bestarticles_news_remove_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('graduated', models.CharField(max_length=50, verbose_name='graduated')),
                ('years', models.CharField(max_length=50, verbose_name='years')),
                ('mentors', models.CharField(max_length=50, verbose_name='mentors')),
                ('work_offers', models.CharField(max_length=50, verbose_name='work offers')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
