# Generated by Django 4.2.3 on 2023-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us/', verbose_name='image')),
                ('file', models.FileField(blank=True, null=True, upload_to='about_us/', verbose_name='file')),
            ],
        ),
    ]
